DECLARE
    P_BCREFNO VARCHAR2(50);
    L_PROD_CODE VARCHAR2(50);
BEGIN   
    P_BCREFNO := '123456';
    SELECT SUBSTR(BCREFNO,4,4) INTO L_PROD_CODE FROM DUAL;
    DBMS_OUT.PUT_LINE('OUTPUT ; ' || L_PROD_CODE);
END;
/